import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import Providers from "@/components/Providers";

const spaceGrotesk = Space_Grotesk({
	variable: "--font-space-grotesk",
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
});

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default async function RootLayout({ children }) {
	const locale = await getLocale();
	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body className={`${spaceGrotesk.variable} font-space antialiased`}>
				<Providers locale={locale} messages={messages}>
					{children}
				</Providers>
			</body>
		</html>
	);
}
